version: '3.9'

services:
  api:
    image: api
    build: ../api
  web:
    image: web
    build: ../web
  vr:
    image: backstopjs/backstopjs:6.3.2
    volumes:
      - ../web:/src
      - ./scripts/backstop-command.sh:/backstop-command.sh:ro
    environment:
      - BASE_URL=http://web:5173
    healthcheck:
      test: [ "CMD-SHELL", "true" ]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      web:
        condition: service_healthy
      api:
        condition: service_healthy
    entrypoint: /bin/bash /backstop-command.sh
