services:
  api:
    image: portfolio-api:${IMAGE_TAG}
    build:
      context: ../
      target: api
    environment:
      - DATA_PATH=$DATA_PATH
  web:
    image: portfolio-web:${IMAGE_TAG}
    build:
      context: ../
      target: web
  vr:
    image: vr:${IMAGE_TAG}
    build:
      context: ../
      target: vr
    depends_on:
      web:
        condition: service_healthy
      api:
        condition: service_healthy
    volumes:
      - vr_volume:/src

volumes:
  vr_volume:
    name: $VR_VOLUME_NAME
