services:
  api:
    image: node:20.10
    volumes:
      - ../api:/src:ro
      - ./scripts:/scripts:ro
    working_dir: /app
    environment:
      - CORS_ORIGINS=http://web:5173
      - SERVER_HOSTNAME=0.0.0.0
      - SERVER_PORT=15000
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:15000/ | grep 'OK' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    command: /bin/bash /scripts/api-command.sh
  web:
    image: node:20.10
    volumes:
      - ../web:/src:ro
      - ./scripts:/scripts:ro
    working_dir: /app
    environment:
      - VITE_API_URL=http://api:15000
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:5173/ || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    command: /bin/bash /scripts/web-command.sh
  vr:
    image: backstopjs/backstopjs:6.3.2
    volumes:
      - ../web:/src
      - ./scripts:/scripts:ro
    environment:
      - BASE_URL=http://web:5173
    healthcheck:
      test: [ "CMD-SHELL", "true" ]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      web:
        condition: service_healthy
      api:
        condition: service_healthy
    entrypoint: /bin/bash /scripts/backstop-command.sh
