services:
  api:
    image: node:20.10
    volumes:
      - ../api:/src:ro
      - ./scripts/api-command.sh:/api-command.sh:ro
    working_dir: /app
    environment:
      - CORS_ORIGINS=http://web:5173
      - SERVER_HOSTNAME=0.0.0.0
      - SERVER_PORT=15000
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:15000/ | grep 'OK' || exit 1" ]
      interval: 1s
      timeout: 1s
      retries: 60
      start_period: 1s
    command: /bin/bash /api-command.sh
  web:
    image: node:20.10
    volumes:
      - ../web:/src:ro
      - ./scripts/web-command.sh:/web-command.sh:ro
    working_dir: /app
    environment:
      - VITE_API_URL=http://api:15000
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:5173/ || exit 1" ]
      interval: 1s
      timeout: 1s
      retries: 60
      start_period: 1s
    command: /bin/bash /web-command.sh
  vr:
    image: backstopjs/backstopjs:6.3.2
    volumes:
      - ../web:/src
    environment:
      - BASE_URL=http://web:5173
    depends_on:
      web:
        condition: service_healthy
      api:
        condition: service_healthy
    command: "test --configPath=backstop.cjs"
